
defaults: &defaults
  workflow:
    - modell: 
      - modell 
    - karosserie: 
      - karosserie
    - motor:
      - motor
    - getriebe: 
      - getriebe
    - aussenausstattung: 
      - farbe 
      - felgen
    - innenausstattung: 
      - radio 
      - klimaanlage
      - navigationsgerät

development:
  <<: *defaults

production:
  <<: *defaults

test:
  workflow:
    - modell: 
      - modell 
    - karosserie: 
      - karosserie
    - motor: 
      - motor
    - getriebe: 
      - getriebe
    - aussenausstattung: 
      - farbe 
      - felgen
    - innenausstattung: 
      - radio 
      - klimaanlage
      - navigationsgerät


